  #  message-0.dispatcher.bccs.svc.cluster.local
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: lighthouse
  namespace: bccs
  # labels:
  #   app: bluelcoud.ccs.dispatcher
spec:
  serviceName: lighthouse
  replicas: 3
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: OrderedReady
  selector:
    matchLabels:
      app: bluelcoud.ccs.cluster
  template:
    metadata:
      labels:
        app: bluelcoud.ccs.cluster
    spec:
      containers:
      - name: bluelcoudccscluster
        image: ccsacr.azurecr.cn/lighthouse:v0222
        imagePullPolicy: Always
        ports:
        - containerPort: 9110
          protocol: TCP
        - containerPort: 4053
          protocol: TCP
        volumeMounts:
        - name: bccs-cluster
          mountPath: /app/akka.hocon
          subPath: akka.hocon
        env:
        - name: ACTORSYSTEM
          value: "bccs"
        - name: CLUSTER_IP
          value: "$(HOST).clustersvc.bccs.svc.cluster.local"
        - name: CLUSTER_SEEDS
          value: "akka.tcp://bccs@lighthouse-0.clustersvc.bccs.svc.cluster.local:4053;akka.tcp://bccs@lighthouse-1.clustersvc.bccs.svc.cluster.local:4053;akka.tcp://bccs@lighthouse-2.clustersvc.bccs.svc.cluster.local:4053"
        - name: HOST
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
      volumes:
      - name: bccs-cluster
        configMap:
          # Provide the name of the ConfigMap containing the files you want
          # to add to the container
          name: bccs-cluster

---
apiVersion: v1
kind: Service
metadata:
  name: clustersvc
  namespace: bccs
  # labels:
  #   app: bluelcoud.ccs.dispatcher
spec:
  ports:
  - port: 9110
    name: server
  - port: 4053
    name: leader
  type: ClusterIP
  selector:
    app: bluelcoud.ccs.cluster